import { ArchiveUnpackerPlugin } from './SceneTree/ResourceLoader/ArchiveUnpackerPlugin.js';
import { JsonLoaderPlugin } from './SceneTree/ResourceLoader/JsonLoaderPlugin.js';
import { TextLoaderPlugin } from './SceneTree/ResourceLoader/TextLoaderPlugin.js';
import { BinaryLoaderPlugin } from './SceneTree/ResourceLoader/BinaryLoaderPlugin.js';
const archiveUnpackerPlugin = new ArchiveUnpackerPlugin();
(window as any).zeaEngine.resourceLoader.registerPlugin(archiveUnpackerPlugin);
const jsonLoaderPlugin = new JsonLoaderPlugin();
(window as any).zeaEngine.resourceLoader.registerPlugin(jsonLoaderPlugin);
const textLoaderPlugin = new TextLoaderPlugin();
(window as any).zeaEngine.resourceLoader.registerPlugin(textLoaderPlugin);
const binaryLoaderPlugin = new BinaryLoaderPlugin();
(window as any).zeaEngine.resourceLoader.registerPlugin(binaryLoaderPlugin);
